#!/bin/bash
# Begin $rc_base/init.d/maui
#
# Based on sysklogd script from LFS-3.1 and earlier.
# Written by Andrew "Weibullguy" Rowland <darowland@ieee.org>
#
# Date: 2007-10-23

. /etc/sysconfig/rc
. $rc_functions

# Read in the command arguments
case "$1" in
    start)
        boot_mesg "Starting Maui Batch Scheduler..."
        loadproc /usr/sbin/maui
        ;;
    stop)
        boot_mesg "Stopping Maui Batch Scheduler..."
        killproc maui
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        statusproc /usr/sbin/maui
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0

# End $rc_base/init.d/maui
