#!/bin/bash
# Begin $rc_base/init.d/ntp

#$LastChangedBy: bdubbs $
#$Date: 2005-08-01 14:29:19 -0500 (Mon, 01 Aug 2005) $

. /etc/sysconfig/rc
. $rc_functions

pidfile=/var/run/ntpd.pid

case "$1" in
	start)
		boot_mesg "Starting ntpd..."
		ntpd -gqx
		loadproc /usr/sbin/ntpd -p $pidfile
		;;

	stop)
		boot_mesg "Stopping ntpd..."
		killproc -p $pidfile /usr/sbin/ntpd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc -p $pidfile /usr/sbin/ntpd
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/ntp
