#!/bin/bash
# Begin $rc_base/init.d/stunnel

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: bdubbs $
#$Date: 2005-08-01 14:29:19 -0500 (Mon, 01 Aug 2005) $

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
        start)
                boot_mesg "Starting the Stunnel Daemon..."
                loadproc /usr/sbin/stunnel
                ;;

        stop)
                boot_mesg "Stopping the Stunnel Daemon..."
                killproc /usr/sbin/stunnel
                ;;

        restart)
                $0 stop
                sleep 1
                $0 start
                ;;

        status)
                statusproc /usr/sbin/stunnel
                ;;

        *)
                echo "Usage: $0 {start|stop|restart|status}"
                exit 1
                ;;
esac

# End $rc_base/init.d/stunnel
